### ISSUE TITLE
Error on Wuxiaworld after login with bearer

### ISSUE THREAD

**Issue by 2kkbi** [lncrawl/lightnovel-crawler#2143]
After putting: lncrawl --login Bearer XXXXX and the novel link when it asked for the query, this popped up. I tried to search it online but I couldnt understand. Hope someone can help me. Thank you.

```Retrieving novel info...
Exception in thread Thread-1 (read_novel_info):
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/lncrawl/templates/browser/basic.py", line 88, in read_novel_info
    self.read_novel_info_in_scraper()
  File "/opt/homebrew/lib/python3.11/site-packages/sources/en/w/wuxiacom.py", line 38, in read_novel_info_in_scraper
    response = self.grpc.request(
               ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pyease_grpc/rpc_session.py", line 150, in request
    response.raise_for_status()
  File "/opt/homebrew/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api2.wuxiaworld.com/wuxiaworld.api.v2.Novels/GetNovel

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/homebrew/lib/python3.11/site-packages/lncrawl/templates/browser/basic.py", line 95, in read_novel_info
    self.read_novel_info_in_browser()
  File "/opt/homebrew/lib/python3.11/site-packages/sources/en/w/wuxiacom.py", line 149, in read_novel_info_in_browser
    self.visit(self.novel_url)
  File "/opt/homebrew/lib/python3.11/site-packages/lncrawl/templates/browser/basic.py", line 65, in visit
    self._visit(url)
  File "/opt/homebrew/lib/python3.11/site-packages/lncrawl/core/browser.py", line 155, in visit
    self._init_browser()
  File "/opt/homebrew/lib/python3.11/site-packages/lncrawl/core/browser.py", line 62, in _init_browser
    self._driver = create_new(
                   ^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/lncrawl/webdriver/__init__.py", line 35, in create_new
    return create_local(
           ^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/lncrawl/webdriver/local.py", line 60, in create_local
    options.add_argument("--lang=%s" % (language or "en-US"))
                                        ^^^^^^^^
UnboundLocalError: cannot access local variable 'language' where it is not associated with a value

 ❗ Error: No chapters found 
<class 'Exception'>
File "/opt/homebrew/lib/python3.11/site-packages/lncrawl/bots/console/integration.py", line 107, in start
    raise e
  File "/opt/homebrew/lib/python3.11/site-packages/lncrawl/bots/console/integration.py", line 101, in start
    _download_novel()
  File "/opt/homebrew/lib/python3.11/site-packages/lncrawl/bots/console/integration.py", line 85, in _download_novel
    self.app.get_novel_info()
  File "/opt/homebrew/lib/python3.11/site-packages/lncrawl/core/app.py", line 137, in get_novel_info
    raise Exception("No chapters found")```

**Comment by krebsf01** [comment]
I am having the same problem

**Comment by alzamer2** [comment]
hello
new update was issued for wuxiaworld.com
update your sources and try scraping
